"""add social

Revision ID: 0bed6d792a3a
Revises: e8415866190a
Create Date: 2018-07-16 15:51:52.850766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bed6d792a3a'
down_revision = 'e8415866190a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'user', ['social_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'social_id')
    # ### end Alembic commands ###
