"""new fields in user model

Revision ID: 450bdcded0bd
Revises: 85ea95619118
Create Date: 2018-06-24 12:15:49.926391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450bdcded0bd'
down_revision = '85ea95619118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
