"""add FK code_id in comment model

Revision ID: 4805eab64376
Revises: 5fa86b01638e
Create Date: 2018-07-20 19:53:13.349941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4805eab64376'
down_revision = '5fa86b01638e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'code', ['code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'code_id')
    # ### end Alembic commands ###
